uepb-campusvii-computacao/EventFlow_Backend

src/controllers/EventController.ts, src/repositories/LoteRepository.ts, src/repositories/UserInscricaoRepository.ts, src/routes.ts
Cria funções necessárias para inativação de lotes no Gerenciador
=> EV-14 - Inativação de Lotes

src/repositories/UserInscricaoRepository.ts, src/services/user/deleteUserByUserId.ts
<Por favor descreva todas as mudanças realizadas e problemas endereçados. Além disso, inclua também toda motivação e/ou contexto relevante, listando toda dependência que estiver diretamente envolvida com as mudanças realizadas.>
Essa PR endereça a(s) tarefa(s) #<task_id>, #<task_id>, #<task_id>...
Essa PR tem como dependências o(s) PR(s) #<pr_id>, #<pr_id>, #<pr_id>...
=> Sistema de multiusuario

src/routes/private/UserPrivateRoutes.ts
<Por favor descreva todas as mudanças realizadas e problemas endereçados. Além disso, inclua também toda motivação e/ou contexto relevante, listando toda dependência que estiver diretamente envolvida com as mudanças realizadas.>
Essa PR endereça a(s) tarefa(s) #<task_id>, #<task_id>, #<task_id>...
Essa PR tem como dependências o(s) PR(s) #<pr_id>, #<pr_id>, #<pr_id>...
=> fix: mostrar atividades

src/controllers/EventController.ts, src/repositories/EventRepository.ts, src/repositories/UserEventRepository.ts, src/repositories/UserInscricaoRepository.ts, src/services/payments/createPaymentUserRegistration.ts
Essa PR adiciona a possibilidade de pagar as inscrições com o cartão de credito ou debito.
Adicione os tokens do mercado pago e crie o pagamento.
=> feat: add card payment method

src/services/payments/createPaymentUserRegistration.ts
Soluciona body de pagamento ao mercadopago. 
```
npm run dev 
```
=> fix: soluciona erro no body da req.

src/repositories/UserEventRepository.ts
add number of subscriptions blocked by max
=> feat: add number of subscriptions blocked by max

src/services/payments/createPaymentUserRegistration.ts
atualiza dateofexpiration
Essa PR endereça a(s) tarefa(s) #<none
=> fix: atualiza dateofexpiration

src/services/payments/createPaymentUserRegistration.ts
Correção de data_of_expiration
Essa PR tem como dependências o(s) PR(s) #NONE
=> fix: format payment date_of_expiration

src/services/payments/createPaymentUserRegistration.ts
fix on format string of dayjs.format()
=> fix: fix on format string of dayjs.format()

src/services/payments/createPaymentUserRegistration.ts
=> fix: revert to static date

src/controllers/UserController.ts, src/services/payments/getPayment.ts
=> fix: retorna getPayment.

src/services/payments/createPaymentUserRegistration.ts
=> fix: conserta nome de rotas.

src/controllers/UserController.ts
Checagem de erros de entrada do mercado pago.
Essa PR endereça a(s) tarefa(s) none
Essa PR tem como dependências o(s) PR(s) none
Fazer um pagamento
=> test: checagem de retorno do mercado pago.

src/services/payments/createPaymentUserRegistration.ts
=> fix: atualiza porta certa ao notificationurl

src/controllers/UserController.ts
=> debug: console.log do action.

src/controllers/EventController.ts
Adiciona novo retorno para o gerenciador.
Ver o dashboard da aplicação gerenciador.
=> feat: adiciona novo retorno ao eventController.

src/controllers/EventController.ts, src/controllers/UserController.ts
=> Dev merge com Master

src/controllers/EventController.ts
merge dev with master
Essa PR endereça a(s) tarefa(s) #<task_id>, #<task_id>, #<task_id>...
Essa PR tem como dependências o(s) PR(s) #<pr_id>, #<pr_id>, #<pr_id>...
Ver painel
=> Dev merge with master

src/services/payments/createPaymentUserRegistration.ts
Soluciona payer first e last name.
Request de pagamento
=> fix: soluciona payer first and last name.

src/services/payments/createPaymentUserRegistration.ts
=> remove: retira aplication_fee para o sercomp.

prisma/migrations/20250408040635_add_turno_to_atividade_model/migration.sql, prisma/schema.prisma, src/controllers/ActivityController.ts, src/repositories/ActivityRepository.ts, src/repositories/UserAtividadeRepository.ts
Reverts uepb-campusvii-computacao/EventFlow_Backend#59
=> Revert "Feat/user activity"

src/repositories/UserAtividadeRepository.ts
Essa PR adiciona uma validação se o usuário não está tentando se inscrever em duas atividades do mesmo tipo no mesmo turno.
Essa PR tem como dependências o(s) PR(s) #58 
Tente se cadastrar em mais de uma atividade do mesmo tipo no mesmo turno, terá que dar errado.
=> feat: add validation to activities from same type to same shift

src/repositories/EventRepository.ts, src/services/payments/createPaymentMarketPlace.ts, src/services/payments/getPayment.ts
CORRIGE EXPORTAÇÃO DE PAYMENT DO MERCADO PAGO.
=> corrige pagamentos e exportação em getpayment.

prisma/migrations/20250408040635_add_turno_to_atividade_model/migration.sql, prisma/schema.prisma, src/controllers/ActivityController.ts, src/repositories/ActivityRepository.ts, src/repositories/UserAtividadeRepository.ts
This reverts commit 676ec3d70dee2056691c46a94b00866e049fa446.
Essa PR reverte uma alteração que foi revertida pois foi feita no lugar errado, agora estamos colocando as alterações de verdade.
=> Reapply "Feat/user activity"

src/controllers/EventController.ts, src/repositories/UserInscricaoRepository.ts, src/routes/private/EventPrivateRoutes.ts, src/services/user/user.service.ts
Essa PR cria uma nova rota para o sorteio de usuarios do gerenciador, modificando um pouco da logica antiga para filtrar o sorteio pelos lotes do evento, alem de refatorar uma parte da função `projectionTableCredenciamento` do `UserIncricaoRepository`
=> feat: add new route, return all users to be drawn in event
